var queriesGoogle = [
	'aller simple syrie',
	'demangeaison de l\'anus',
	'manger peau de saucisson danger',
	'draguer fille facilement',
	'passer la friendzone',
	'comment supprimer historique',
	'kim kardashian nue image',
	'capitale de londres',
	'acheter poupee gonflable',
	'kama dofus',
	'mariage chien législation',
	'devenir sugarbaby',
	'comment se faire des amis',
	'lubrifiant maison',
	'sex shop proche',
	'je suis peut etre gay',
	'bing',
	'morandini.fr',
	'on va la pécho',
	'participer a tpmp',
	'admission kkk',
	'aller dans le darknet',
	'zaz fée chez moi',
	'combien de jour dans une semaine',
	'fille de l\'est facile',
	'comment se battre',
	'vbucks facile',
	'forum 18/25',
	'égalité et réconciliation',
	'achat sweat baby milo',
	'secret story inscription',
	'comment hacker facebook',
	'saignement uretre',
	'alfred einstein',
	'compilation nekfeu sourire',
	'toy story r34',
	'blue waffle',
	'1 boy 1 jar',
	'2 girls 1 cup',
	'diams compil 1 heure',
	'adopter fille de 18 ans',
	'comment se radicaliser',
	'toucher le rmi',
	'devenir acteur porno',
	'grosculs.com',
	'chatroulette',
	'pornhub premium',
	'habiter vesoul',
	'swag signification',
	'se faire tatouer un cochon',
	'mykonos aller simple',
	'nichon png',
	'maroc chirurgie',
	'pnl tube de l\'été',
	'fanfiction herry potter',
	'sexy animé théories',
	'sodomie en anglais',
	'distiller son alcool',
	'apprendre l\'internet',
	'télécharger wifi',
	'impressionner en société',
	'j\'ai un pied plus grand que l\'autre',
	'3x3',
	'OVNI terrestre',
	'prince du gabon offre',
	'bel homme feminin',
	'posséder des reptiles kezako',
	'ouvrir un cadenas sans clé',
	'survivre à Aubervilliers',
	'Jul président',
	'Lafouine baston',
	'Google',
	'pourquoi je trouve ma mere est jolie',
	'oornhub',
	'se faire débloquer de facebook',
	'télécharger compte bancaire',
	'présent conjugaison',
	'erection incontrolee',
	'lisa ann',
	'riley reid',
	'chié mou',
	'mon internet est incontrolable',
	'hacked by FlmabyKiller29',
	'donald trump sexualite',
	'reproduction grand singe',
	'smegma calorie',
	'poeme a envoyer',
	'voyance en ligne',
	'paire de charentaises',
	'pussy fart traduction',
	'pet humide',
	'gode michel',
	'206 renault gti',
	'anal express vostfr',
	'vierge a 24 ans',
	'manger le jonc signification',
	'blague drole site web',
	'calorie crotte de nez',
	'verlan de chelou',
	'smegma image',
	'allah vs dieu',
	'fdesouche abonnement',
	'echangisme sur lyon',
	'tinder telecharger',
	'robert pattinson torse nu',
	'gout ciprine',
	'sexe gallinacé',
	'dictonnaire laurent baffie',
	'cacher un corps legalement',
	'best of baba 4/3',
	'jean michel sartre bio',
	'nelson mandela ou morgan freeman',
	'christophe dechavanne',
	'comprendre son homme',
	'abonnement entrevue',
	'couille bleue',
	'david lafarge scoop',
	'dany boon illuminati',
	'couleur sexe michael jackson',
	'michel drucker vampire',
	'macron ou micronde',
	'achetez tondeuse pubienne',
	'touches collantes',
	'confession curé en ligne',
	'ça va vous ?',
	'pokemon irl',
	'GN Rambouillet',
	'planter son pote',
	'lego coincé anus',
	'télécharger 100euros',
	'pirater pentagon français',
	'jp papin gif',
	'moussaka au sperme',
	'01.net',
	'grindr compte premium',
	'vendre son rein',
	'leboncoin tourcoing',
	'se muscler rapidement',
	'congé paternité sans enfants',
	'simuler au lit',
	'jeu de tir irak',
	'citation jean paul rouve',
	'hitler bande dessinee',
	'apprendre la bourse boursiere',
	'sandales pas cheres et jolies',
	'hello kitty catch',
	'diablox9',
	'fantasme mylittlepony',
	'retirer bic rectum',
	'acheter une vente',
	'pourquoi j\'ai mal ici' ,
	'devenir moine procedure',
	'sos racisme antiblanc',
	'roux ou roue',
	'penis olivier giroud',
	'nikos alliagas bronzage',
	'comment contenter une femme',
	'empoisonner le chien du voisin',
	'la mère de M Pokora fait quoi comme métier',
	'les villes du monde se trouvent dans quels continents européens',
	'joueurs blancs equipe de france',
	'andré rieu concert',
	'sos homme battu',
	'lol 3v3 backlane comp',
	'comment lancer une recherche sur Google ?',
	'combi SM neuf',
	'zidane coup de boule 10h',
	'lettre après z',
	'cartouche gitane import export',
	'fume la vie avant que ?',
	'fesses de griezmann',
	'être délire dans une fete',
	'cheddar brulant sur les tetons',
	'irritation prépuce',
	'insulter un gay poliment',
	'tuto titanic accross the map',
	'raisons de vivre',
	'moyenne taille penis en france',
	'sexe avec cousine risque',
	'pornodingue',
	'gagner en assurance',
	'il m\'entraîne, au bout de la nuit',
	'manger ver de terre vidéo',
	'être populaire au college',
	'high school musical acteur',
	'pere noel existe il',
	'cannibal holocaust dvdrip',
	'mein kampf résumé',
	'thierry beccaro autographe',
	'blablaland',
	'cheat code adibou',
	'devenir sjw',	
	'gipsy king retour',
	'sextoy connecté',
	'ghetto millionaire',
	'jackie sardou image',
	'quel heure est-il',
	'rite satanique tuto',
	'tutoriel cocktail molotov',
	'se débarasser de ses menottes',
	'etre fiché S',
	'marabout en ligne',
	'acheter drogue dure',
	'menopause a 20 ans',
	'apprendre le turc en 24h',
	'capote percée risque',
	'anal ou annale',
	'hitler existe il ?',
	'11 septembre compil',
	'top 10 des prenoms de femmmes qui puent de la chatte',
	'spoil film marvel',
	'dorcel store',
	'meilleure position kamasutra',
	'meme raciste',
	'lichtenstein est il un vrai pays',
	'télécharger virus',
	'do a barrel roll',
	'j\'ai honte de mon corps',
	'je me déteste',
	'se procurer cyanure',
	'mort au rat achat',
	'banque de sperme paris',
	'orgasme asmr',
	'spaghetti en italien',
	'alexis texas',
	'prostitution loi',
	'tokyo hotel concert',
	'passer la frontiere illegalement',
	'prise RDV urologue st ouen',
	'abonnement télé Z',
	'habbo hotel',
	'marge simpson sexy',
	'origami bite',
	'se desinscrire du web',
	'qui veut parler avec moi',
	'les tuches fous rires',
	's\'épiler le scrotum',
	'commment eviter de donner pourboire',
	'gangster2tess',
	'contacter cortex91',
	'harry potter existe',
	'demander la nationalité berlinoise',
	'boire de l\'essence',
	'les syriens du metro sont ils roumains',
	'pqsser clqvier en qwerty',
	'purepeople',
	'gentside sexlife',
	'boeuf bourgignon vegan',
	'pet qui sente bon',
	'combat serpent vs araignee',
	'comment mourir lentement',
	'mes dents sont transparentes',
	'est ce normal de vomir lorsque l\'on a trop mangé',
	'pourquoi ça pue quand on pete',
	'j\'ai accidentellement construit une étagère',
	'mon collègue me drague',
	'faut-il mettre deux capotes',
	'HTML maladie',
	'michael loeb prix spectable',
	'christophe lamber rire 2h',
	'how to eat ass',
	'je veux devenir vegan mais j\'aime pas les legumes',
	'mourir sans douleur',
	'se forcer a dire mamene',
	'bigflo et oli playlist',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
]; 

function getRandomValueFromArray(arrayName){
	var randomValue = arrayName[Math.floor(Math.random() * arrayName.length)];
	return randomValue;
}

function searchOnGoogle(query){
	window.open('http://google.com/search?q='+query, 'newTab');
}

document.getElementById('search').onclick = function() {
	
    setInterval(() => {
    	randomQueryGoogle = getRandomValueFromArray(queriesGoogle);
    	searchOnGoogle(randomQueryGoogle);
    }, 1000);

};
